### ISSUE TITLE
Error Downloading from readcomiconline.li

### ISSUE THREAD

**Issue by SomeGuyKai** [RedSquirrel87/manga-downloader#791]
It's giving me an error when I try to download comics from readcomionline.li

URL: https://readcomiconline.li/Comic/Star-Wars-Darth-Vader
Error Msg: 

12:40:29:  Getting pages list for chapter Star Wars: Darth Vader (2020) Issue #32...
12:40:30:  Error while getting pages list!

[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/11325337/jvm_log.txt)

Thank you for all you do

**Comment by RedSquirrel87** [comment]
I just tested and it works for me here:

![image](https://user-images.githubusercontent.com/1155596/234360480-f6d0b734-affb-4198-b538-1ca295b8a184.png)

Are you sure you didn't download too fast or too much stuff and got a temporary ban/captcha lock? If it happens with any comic of the site try waiting for about 24 hours and then try again and let me know

**Comment by SomeGuyKai** [comment]
Strange. I am able to go to the site and view different comics and nothing pops up asking me to do a captcha or anything. I'll try the downloader again in 24 hours and get back with you.

**Comment by RedSquirrel87** [comment]
> Strange. I am able to go to the site and view different comics and nothing pops up asking me to do a captcha or anything. I'll try the downloader again in 24 hours and get back with you.

This was the first time you were downloading from them using Manga Downloader? I mean, it worked for you before or you never be able to download from the website with the app?

**Comment by SomeGuyKai** [comment]
This was the second series I tried to download with the app. First one was fine and dandy. It could only download 3 chapters of this series before it started to error out. I just tried to download the walking dead series and marvel zombies and they both give me the same error.

**Comment by RedSquirrel87** [comment]
From what you're saying it seems indeed that the site has blocked you in some way, since it allowed you to download and only after a certain number of downloads it doesn't let you do it anymore. But frankly I tried to download a whole comic just now and still didn't get any block, so it seems really strange that you could get it, and after just 3 chapters.

![image](https://user-images.githubusercontent.com/1155596/234540960-b06584d4-6302-4a32-829b-ea919e0d990e.png)

I did my test with 1 second waiting between downloading pages and 2 chapters downloaded at the same time (which are the lowest settings for non-subscribers) and it gave me no issue whis way 🤔

**Comment by RedSquirrel87** [comment]
Just to be sure I just tried also with the same comic above ( https://readcomiconline.li/Comic/Star-Wars-Darth-Vader ) and despite all the downloads done before, this one also downloaded without issues:

![image](https://user-images.githubusercontent.com/1155596/234545421-6c13dac2-0ad3-4be7-acbc-8e7ff71b16c7.png)

If you haven't set the parameters lower (but I don't think since it would require a Patreon subscribtion) it's really hard to figure out why that happened 🤔
Please later let me know if today, after 24 hours, you can download again

**Comment by SomeGuyKai** [comment]
Afternoon, I was finally able to get it working again. I tried it again this morning, and it was giving me the same error. So I cleared my cookies in firefox, same error. So I tried to visit the site in Edge, and the bot captcha came up, verified myself and everything is fine and dandy now. I might have to periodically visit with an incognito tab and make sure that I'm not tripping any bot verification.

Sorry for all the trouble.

Thanks again!
