### ISSUE TITLE
bato not working

### ISSUE THREAD

**Issue by nooususa** [RedSquirrel87/manga-downloader#792]
bato.to and batotoo.com, the internet network that I use is no longer working, can you add it so that you can use other bato links, for example hto.to or something else, please

**Comment by RedSquirrel87** [comment]
Do you mean that bato.to has been blocked by your ISP? Because I just tested and they work for me here 🤔
Anyway, if the framework is the same for all then you can already use the specific function to change domains in the Edit menu without the need to wait for the new version of the program.

Also, could you please list me all the bato.to alternatives domains? So that I can add them all togheter to the program for the next release, thank you

**Comment by RedSquirrel87** [comment]
After a quick research I found these mirror domains: comiko.net, batotoo.com, battwo.com, batotwo.com, mangatoto.com, mto.to, hto.to
Do you know any others?

**Comment by nooususa** [comment]
yes the domain bato.to batotoo.com has been blocked on my internet path,

if possible, please, add another link, for example, hto.to, mto.to because that's the only link that can be accessed by me, thank you

**Comment by nooususa** [comment]
https://zbato.org/
https://zbato.net/
https://zbato.com
https://xbato.net
https://xbato.org/
https://xbato.com
https://readtoto.com/
https://readtoto.org
https://readtoto.net

**Comment by nooususa** [comment]
just for a while,
please for the next update the link can be downloaded, thank you

**Comment by RedSquirrel87** [comment]
> https://zbato.org/ https://zbato.net/ https://zbato.com https://xbato.net https://xbato.org/ https://xbato.com https://readtoto.com/ https://readtoto.org https://readtoto.net

Thank you, I'll try to add them all for the next version 👍

**Comment by nooususa** [comment]
Thank you, 👍👍🤩🤩

**Comment by RedSquirrel87** [comment]
v61 released, it adds support for many batoto mirror websites
