### ISSUE TITLE
Unable to bypass anti-bot protection with Manga Downloader Assistant

### ISSUE THREAD

**Issue by nexist418** [RedSquirrel87/manga-downloader#799]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

I started Manga Downloader and received a box telling me to install the Assistant and paste the results. I did so. It then tells me to use the Force button. I did so.  It fails.

I am running: 
- Windows 11
- Manga Downloader v60.2
- Brave 1.57.49
- Edge Version 116.0.1938.54 (Official build) (64-bit)
- The latest Assistant from each store

JVM_LOG.txt
```
[Thu Aug 24 15:31:58 PDT 2023] Program started.
[Thu Aug 24 15:31:58 PDT 2023] MangaDownloader v60.2
[Thu Aug 24 15:31:58 PDT 2023] OS: Windows 11 (amd64) | JVM: 1.8.0_381
[Thu Aug 24 15:31:59 PDT 2023] [DB] Database current version: 5
[Thu Aug 24 15:32:04 PDT 2023] Loading manga from https://mangadex.org/title/aa6c76f7-5f5f-46b6-a800-911145f81b9b/sono-bisque-doll-wa-koi-wo-suru
[Thu Aug 24 15:32:04 PDT 2023] HTTP response code: 503
[Thu Aug 24 15:33:47 PDT 2023] HTTP response code: 503

```
<img width="1426" alt="2023-08-24 15_34_00-Home Page and 13 more pages - Personal - Microsoft​ Edge" src="https://github.com/RedSquirrel87/manga-downloader/assets/58746683/cf77bfba-b996-49a8-bb5b-d70b5db127ff">
<img width="1846" alt="2023-08-24 15_34_18-Manga Downloader v60 2 by Red Squirrel (http___redsquirrel87 com)" src="https://github.com/RedSquirrel87/manga-downloader/assets/58746683/2add7367-d29b-46c4-bab3-8b14bf9f7d3d">

**Comment by RedSquirrel87** [comment]
The anti-bot protection is when you're getting the http 403 error, 503 is a totally different error caused by server temporary issues (you can find more info about the http 503 error here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503 ). So it's normal you can not bypass it with MDA, this is not a bug.

P.s.: on their Discord channel they announced that they have server issues since yesterday, surely this is related to that:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/213e04d2-cf05-4b1d-ad4c-d8bedac3516d)

**Comment by nexist418** [comment]
Yay. Heck, it even works now.
