### ISSUE TITLE
Update v61.3 broke bookmarks for me somehow.

### ISSUE THREAD

**Issue by quanti5** [RedSquirrel87/manga-downloader#802]
I had the program open for about a week, and when I closed and relaunched it it had updated to v61.3. I then noticed my bookmarks weren't working as they used to. The View->Bookmarks (Alt+B) page doesn't populate anymore and is blank. I know I have at least some bookmarks but the Change manga popup window only displays series with titles starting from A to E. Anyones labeled F and onward are invisible/inaccessable to me and cannot be accessed without pasting the original link again. I do not remember all of them which is why the bookmark feature was so helpful.

Thank you for your time.

[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/12512111/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
From what I read in the log the issue is caused by a COMIKO manga you had in your bookmarks:
`No enum constant mainpackage.Website.COMIKO`
this because now it has been renamed to a generic "BATOTOMIRROR" together with the other domains added in v63. 
I'll release a backward compatibily fix as soon as possible 👍

**Comment by RedSquirrel87** [comment]
v61.4 released, it should fix the COMIKO issue, please let me know if it works for you too 😉

**Comment by quanti5** [comment]
Wow! Thanks for identifying the issue so quickly.

**Comment by quanti5** [comment]
Updated to v61.4 and the issues I saw are seemingly fixed. Thank you so much.
