### ISSUE TITLE
MangaToon and Reaperscans are Non-Functional

### ISSUE THREAD

**Issue by Solarnism3** [RedSquirrel87/manga-downloader#803]
Hi Red Squirrel,

I have sent you an email regarding this, but I will post it here again to quickly have your attention.

Hope you are doing well and thanks for providing such a useful application.

I have tested multiple sites and it works well with most of them, except **mangatoon.mobi** and **reaperscans.com**.

Tried MDA but also failed. Can you take a look and/or reply to my email?

Thanks,
Solarnism
[jvm_log.txt](https://github.com/RedSquirrel87/manga-downloader/files/12551766/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Yeah, reapearscan is not working for now (you can find the websites known status in the table on input dialog), we need to find a new way to bypass its cloudflare anti-bot protection from a JAVA desktop app. 
About mangatoon, I don't know why you're getting a 403 error, maybe you have been IP banned or you're in a country where it's blocked by DNS? I just tried and it works for me here, without even the need of MDA:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/d56b2931-f7f1-4db8-8493-91da7d10791a)

**Comment by Solarnism3** [comment]
Hi Red Squirrel,

Thanks for the updates.

Regarding MangaToon, yes, I have to use a VPN add-on in order to access the site, but that is a matter of the browser. Didn't think it would affect the Manga Downloader as well as it is a stand-alone application. So how can I fix this?

**Comment by RedSquirrel87** [comment]
You could try to delete the cookies.dat file from the program's folder, maybe you have some cookie which gives issue with Mangatoon

**Comment by RedSquirrel87** [comment]
> Hi Red Squirrel,
> 
> Thanks for the updates.
> 
> Regarding MangaToon, yes, I have to use a VPN add-on in order to access the site, but that is a matter of the browser. Didn't think it would affect the Manga Downloader as well as it is a stand-alone application. So how can I fix this?

You should configure your VPN to apply to your system network and not only to the web browser, MD is a JAVA desktop app so it connects to internet using your system network, it has nothing to do/share with the web browser

**Comment by Solarnism3** [comment]
Thanks. Will get a proper VPN software and try.

In the meantime, can we possibly have any way to remove the watermark?

**Comment by Solarnism3** [comment]
Working well and fast with a proper VPN. But I assume we can only download the free chapters?
[https://prnt.sc/hTrmCD2EdMlb](url)

**Comment by RedSquirrel87** [comment]
If you are referring to the logo "Mangatoon" unfortunately it does not seems to be an extra pic that can be avoided to download, it's printed above the images which reside on their server (the ones showed on the web and the ones the program downloads) so it is not possible to avoid it, sorry :(
For that you can use any specific graphic editor tool (or online services like https://www.watermarkremover.io/ and similar)

**Comment by RedSquirrel87** [comment]
> Working well and fast with a proper VPN. But I assume we can only download the free chapters? [https://prnt.sc/hTrmCD2EdMlb](url)

Yes, with MD you can download only free chapters by default, it's a policy that has been adopted since the first moment to avoid giving the way to get paid content and spread it for free. Scanlations are already a very gray area of legality in many countries, a similar possibility would definitely raise unwanted attentions by the websites owners and it's always better let sleeping dogs lie xD

**Comment by Solarnism3** [comment]
This site: **dragontea.ink** is using Madara theme but looks like it also has the same security protocol as reaperscans, so it is not possible to reach it.

Really appreciate you taking a look :D.

**Comment by RedSquirrel87** [comment]
Yeah, they uses the same cloudflare protection (in addition to javascript obfuscated code), until we find a new method to bypass the latest generation cloudflare antibot protections using a desktop JAVA application unfortunately there is no possibility to support similar websites

**Comment by Solarnism3** [comment]
Hi Red,

I see that comico.jp is already on your list so you may also consider its English version, aka pocketcomics.com, as well?

I don't mind topping up and paying for the chapters, but it will really be a pain to download each image manually :D.

Cheers!

**Comment by bumbaras** [comment]
> Yes, with MD you can download only free chapters by default, it's a policy that has been adopted since the first moment to avoid giving the user a way to get paid content and spread it for free. Scanlations are already a very gray area of legality in many countries, a similar possibility would definitely raise unwanted attentions by the websites owners and it's always better let sleeping dogs lie xD

I must argue with Your standing - I really like Your app, but it is already shady enough even without downloading protected content. It's for downloading mangas (manhwas, manhuas) and it already allows to spread the downloaded content further. I would agree if Your app had the algorithms to allow download protected content by any user, not legitimate one. By legitimate I mean user who has account on given site and bought the content. Of course it's Your app and Your rules but two notices:
- You assumed the reader who will download anything will have an urge to give it away to internet,
- No one will care enough if Your app allow to download from shady sites.
Both are untrue in my opinion, and users who really paid for content won't be willing to share it in internet due to possibility of account ban and lawsuit from publisher - paid accounts are rarely anonymous. Well, i wouldn't risk. Most sites are built the way where You can't easily download content without additional tools - try to download from Webtoon Line using only browser downloader.
As a publisher I wouldn't like Your app even if it allows only to get "my content" from pirated sites.
