### ISSUE TITLE
LeviatanScans Domain Changed to lscomic.com

### ISSUE THREAD

**Issue by SpiralKipz** [RedSquirrel87/manga-downloader#804]
New format seems to be

`https://lscomic.com/manga/[title]/[chapter]`

E.g.
`https://lscomic.com/manga/tale-of-a-scribe-who-retires-to-the-countryside/chapter-173/`

If this is the wrong way to mention changes like this that remove functionality from the base app then my apologies.

**Comment by RedSquirrel87** [comment]
Please do not worry about reporting an issue, first of all because this is the right way but also because reporting an issue, even in the wrong way, is still always useful since obviously I don't use this application every day (and certainly when I do I don't try all the myriad of supported sites anyway) so every bug report is always welcome because it will improve the program for everyone 👍
About the domain changes I'll see to add support for the new one in next version, thank you for reporting the issue

**Comment by SpiralKipz** [comment]
Awesome, thank you!
