### ISSUE TITLE
manhuascan.com don't working

### ISSUE THREAD

**Issue by yurilovegl** [RedSquirrel87/manga-downloader#805]
We can fix this, the manga chapters don't load, don't show anything and don't give an apparent error.
If you can agree I would be grateful. Thanks.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, I'll try to fix this in next version 👍

**Comment by Solarnism3** [comment]
Looks like sites using the Manga Reader theme, such as asuracomics.com, mangasect.com, nightscans.net, etc are currently not working as well.

Appreciate you taking a look at them.

**Comment by Solarnism3** [comment]
I'm now a paying member lol but it's so sad that no chapters from likemanga.io can be downloaded for now.

Check this screenshot: https://prnt.sc/mneRhUHvZtTd

Nice to get it fixed asap.

**Comment by RedSquirrel87** [comment]
> I'm now a paying member lol but it's so sad that no chapters from likemanga.io can be downloaded for now.
> 
> Check this screenshot: https://prnt.sc/mneRhUHvZtTd
> 
> Nice to get it fixed asap.

From the screenshot it seems to be an issue related to the relative paths they started using for their links, it should not be too difficult to fix this. I'll see to release a fixed nightly build tonight for this and of course it will be fixed also in next public release

**Comment by RedSquirrel87** [comment]
About My Manga Reader CMS, maybe they changed something in the framework and that broke support for all the websites which have been updated to the new framework. I'll see if it's possible to fix it quickly so as to insert also it into tonight nightly build, otherwise it will be fixed in the next ones.

**Comment by RedSquirrel87** [comment]
I just tested asuracomics, they are not using the My Manga Reader CMS, they use an internal Manga Stream framework. In this case asuracomics does not work anymore because they changed their domain to asuratoon.com, if you're a patreon supported you can already fix this by changing the supported domain with the specific function you can find under the "Edit" menu in the program ;)
Anyway I'll fix this for everyone in next version

**Comment by Solarnism3** [comment]
I've tried asuratoon.com, asuracomics.com, asurascans.com but sadly nothing worked (does it work for you?)

Not only asuratoon, but all the sites using this same framework (mangasect.com, manjanoon.net for example) don't seem to work anymore.

**Comment by RedSquirrel87** [comment]
As stated above, https://asuratoon.com/ changed their domain into https://asuratoon.com, you need to change the domain supported by the program with the specific function under the Edit menu to support it:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/3a1fcffc-279d-489a-ac49-30d19b3258ff)
Or just wait for next release where the domain will be updated for everyone.
About the other websites, currently they are not supported by the program since the framework used by these websites (Manga Stream) is not between the generic ones the user can currently select (but I plan to add it into the nightly build I'll release tonight). I tested it with nightscans and it seems to work, but not for mangasect (probably they changed something in their website and this broke the standard framework support).

**Comment by Solarnism3** [comment]
The chapter list is showing up, but no chapters are successfully downloaded from asuratoon: https://prnt.sc/U0nq9v0KSLpK

I don't even have any success with manjanoon or nightscans. So wait for your update on the framework tonight?

**Comment by RedSquirrel87** [comment]
> The chapter list is showing up, but no chapters are successfully downloaded from asuratoon: https://prnt.sc/U0nq9v0KSLpK
> 
> I don't even have any success with manjanoon or nightscans. So wait for your update on the framework tonight?

Please try to check in the download path, you should find the download images xD
That message is simply an issue with placeholder/banners/fake images they use on their server, but apart from that single useless image you should have downloaded the others without problems ;)
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/8f400bf2-1afb-4b8c-b51a-d578bf021471)

**Comment by RedSquirrel87** [comment]
About the other websites yes, asurascan is the only publicy available for now, the others are not available or compatible with the current public release

**Comment by Solarnism3** [comment]
No, sorry for that. I edit the domain of 4 sites lightscans.fun, magusmanga.com, manjanoon.net, nightscans.net which are using the same framework as asuratoon.com, and they all worked and chapters have been successfully downloaded :D.

It's just that there seem to be no way to access sites using the same framework but also use CloudFlare lol like cosmicscans.com or void-scans.com.

About chapters from asuratoon, yes they are here now :D.

**Comment by RedSquirrel87** [comment]
Yeah, the only countermeasure this program can use against Cloudflare antibot protection is the cookie-way using web extension (Manga Downloader Assistant), if that method does not work then unfortunately there are no other ways currently known to bypass the problem

**Comment by Solarnism3** [comment]
Tried kaiscans.com several times but failed, can you take a look? I guess it is the same case with mangasect.com.

**Comment by RedSquirrel87** [comment]
This seems to work using the generic framework option (that will be in the upcoming version):
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/819d19d0-7a3f-42a1-90b6-3ae8b9fb2a01)
I tried with this manga: https://www.kaiscans.com/series/cry-even-better-if-you-beg/

**Comment by RedSquirrel87** [comment]
There is no limit set by me for bookmarks number, so the only limits is how many data can handle your hardware (between RAM for JVM and space for database). 
About the second question, yes, all the downloaded files will be written in the output folder you can set from program settings, and if you want to customize how the chapters should be saved and sorted/named you can do it simply by using the specific advanced function you can find in the _Edit_ -> _File naming scheme_ menu

**Comment by Solarnism3** [comment]
So new chapters when downloaded, will go to their appropriate manga folders, instead of all new chapters (of multiple titles) going into one folder (aka named "Update"/"New chapters" or something).

In that case, can we export the updated list so that I know which manga has new chapter(s), in case I accidentally close the MD and all the data is erased?

**Comment by RedSquirrel87** [comment]
Do you mean the downloaded new chapters, correct? Or the list of manga which have new chapters (but not downloaded yet)?

**Comment by Solarnism3** [comment]
Actually both are fine.

I can download new chapters to their existing manga folders first, and then export a list/log of downloaded new chapters (including date, time, list of new chapters and title names, etc) so that I can quickly know which manga they belong, so I can easily find and open these exact folders to upload new chapters to the sites.

Or, I will run a check first, then export a list/log of manga that have new chapters, whether I download them or not. First run a check and save the list, then come back to download those new chapters later whenever I want.

If I have thousands of manga folders that constantly add new chapters everyday, the daily logs/lists everytime I run a check will be very convenient.

**Comment by Solarnism3** [comment]
Hi Red, I've just checked and see that mangasy.com is on the supported list but somehow the chapters can't be downloaded for now. Can you take a look?

**Comment by RedSquirrel87** [comment]
> Hi Red, I've just checked and see that mangasy.com is on the supported list but somehow the chapters can't be downloaded for now. Can you take a look?

It seems they crypt their pages links now, this will going to take some work, I'll see if I can work on it over the weekend and fix it

**Comment by Solarnism3** [comment]
Hi Red, somehow I can bypass the dragontea.ink's CloudFlare protection and get the chapter list, but they seem to be doing something to the page links as well, maybe you can take a look while checking manhuasy.com.

Also, the manhuamix.com (Madara framework) is working quite fine, but the page links of certain chapters also don't work. You can check out chapters around 335-385 of this manga: https://manhuamix.com/manhua/spicy-wifes-reborn-world-manhua/ and see if you can do something about it.

**Comment by RedSquirrel87** [comment]
Yes, dragontea crypts the page link in the same way of mangasy (with the addition of an URL encoding procedure).
About Manhuamix, it's the same fake issue of Asuratoon, simply there is a placeholder page (linked at https://manhuamix.com/wp-content/uploads/WP-manga/data/manga_624ac37c89b58/66fe5ac7b806bbbf8abf5bcddb1256ac/manhuamix.com--.jpg ) that it does not exist, but this has nothing to the with the chapters pages which should be downloaded with no issue anyway (check at download path) ;)
