### ISSUE TITLE
Why download limit???

### ISSUE THREAD

**Issue by Mangalover123** [RedSquirrel87/manga-downloader#808]
Why i can't download more than 10 manga/manhwa chapters.
Why is there a limit to download.

**Comment by RedSquirrel87** [comment]
You can download as many chapters as you want, there is no limit. The only existing limit is on **simultaneous** downloads, but it was calculated after various tests which highlighted how higher values only create problems both for the JVM itself (which obviously requires more resources and often ends up crashing or giving errors) and for the servers of the various sites, because the more simultaneous requests you make, the greater the risk of detection of false DDOS attacks by the servers (since it is certainly not "normal" to make so many simultaneous requests from the same source) and therefore they end up blocking you or even banning your IP. Furthermore, each of that request is a full download function that brings with it dozens of subfunctions and separate threads, each of which can run into dozens of different problems and managing hundreds of them would not be healthy at all for the program. The maximum value of 10 was the best compromise to avoid all this.
If you don't mind dealing with the aforementioned consequences I can also remove the limit, no problem, but it exists because I'm sure that most users would then come here to open bug reports that it doesn't work or that it crashes with 100+ simultaneous downloads, or even complaining that they got banned from x website xD

**Comment by Mangalover123** [comment]
Well i did not think you would reply this fast but the issue is with the website 
bilibilicomics.com
if you know any method to fix this i would be happy to follow it.

**Comment by RedSquirrel87** [comment]
I just tried with a random manga of bilibilicomics.com and I could download much more than 10 chapters. What's the link of the manga whick gives you this issue?

**Comment by Mangalover123** [comment]
It's actually more than one link but the one i have the issue with
https://www.bilibilicomics.com/detail/mc440
after the 13 chapter it's just 2 images per chapter

**Comment by RedSquirrel87** [comment]
If you open the website in your web browser you can see that it's not na error, there are indeed only three images in those chapters:
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/aadb69bd-51bd-49f9-8f7f-3793d50f29d3)
Since one is the splashscreen, the program finds and downloads only the other two pages. This is not a bug, it's the way the website works, it shows only those images to free users. You can try to import your cookie session (from the Edit -> Cookie Management menu) but I don't know if it will be enough

**Comment by Mangalover123** [comment]
Thank you for your help i will try the Cookie Management Menu method and hope it will help.
