### ISSUE TITLE
Bato sites are failing based on "Error: unable to find BATOPASS variable."

### ISSUE THREAD

**Issue by surfrock66** [RedSquirrel87/manga-downloader#812]
Trying to download from any bato v3x site is giving an error looking for "BATOPASS" variable, which I don't see a way to input.

>When you report an issue please be sure to:
```
[Fri Jan 05 11:16:53 PST 2024] Program started.
[Fri Jan 05 11:16:53 PST 2024] MangaDownloader v61.4
[Fri Jan 05 11:16:53 PST 2024] OS: Linux (amd64) | JVM: 17.0.9
[Fri Jan 05 11:16:54 PST 2024] Patreon status: no linked Patreon account.
[Fri Jan 05 11:16:54 PST 2024] [DB] Database current version: 5
[Fri Jan 05 11:16:57 PST 2024] Database backup created successfully!
[Fri Jan 05 11:17:02 PST 2024] Loading manga from https://zbato.org/title/79388-one-punch-man-official
[Fri Jan 05 11:17:04 PST 2024] HTTP response code: 200
[Fri Jan 05 11:17:04 PST 2024] Framework: BATOTOV3XMIRROR
[Fri Jan 05 11:17:05 PST 2024] 237 chapters found.
[Fri Jan 05 11:18:13 PST 2024] Download started for chapter Chapter 196
[Fri Jan 05 11:18:14 PST 2024] Error: unable to find BATOPASS variable.
```

**Comment by RedSquirrel87** [comment]
Probably they changed something in their code, I'll check and release a fix (I wanted to release the new version this weekend but at this point I'll try to fix this first and release later with everything fixed). Thank you for reporting the issue

**Comment by surfrock66** [comment]
Much appreciated, this project is amazing!

**Comment by forkirara** [comment]
It's strange because it works for me (bato.to and mirrors)
`[Wed Jan 10 08:54:40 CET 2024] Program started.
[Wed Jan 10 08:54:40 CET 2024] MangaDownloader v61.4
[Wed Jan 10 08:54:40 CET 2024] OS: Linux (amd64) | JVM: 17.0.9
[Wed Jan 10 08:54:42 CET 2024] Patreon status: no linked Patreon account.
[Wed Jan 10 08:54:42 CET 2024] [DB] Database current version: 5
[Wed Jan 10 08:58:42 CET 2024] Loading manga from https://bato.to/title/131561-i-hold-the-tyrant-s-heart-official
[Wed Jan 10 08:58:42 CET 2024] HTTP response code: 200
[Wed Jan 10 08:58:42 CET 2024] Framework: BATOTOV3X
[Wed Jan 10 08:58:43 CET 2024] 31 chapters found.
[Wed Jan 10 08:59:08 CET 2024] Download started for chapter Chapter 31
[Wed Jan 10 08:59:08 CET 2024] 39 pages found for chapter Chapter 31`

**Comment by surfrock66** [comment]
Hmm, it's doing the same for me still, version 61.4 on Linux:

Are you storing something fro BATOPASS somewhere?  I have a Bato account, but don't see a place to enter credentials or anything?  Are you using an alternate Bato url?

**Comment by RedSquirrel87** [comment]
It was an issue related only to mirror sites (those ones using the BATOTOV3XMIRROR framework) , I've already fixed it in the nightly build that will be released tonight 👍
About the public release, it is already scheduled for the weekend (hoping no new issues emerge xD)

**Comment by RedSquirrel87** [comment]
v62 just released, it should fix this issue
