### ISSUE TITLE
Mangaplus error

### ISSUE THREAD

**Issue by Pandeonidae** [RedSquirrel87/manga-downloader#832]
When attempting to access https://mangaplus.shueisha.co.jp/titles/100037 (Chainsaw Man):
![image](https://github.com/RedSquirrel87/manga-downloader/assets/171721122/edb29df4-0cc0-4792-b56f-eabfc6bfe2ba)

[jvm_log.txt](https://github.com/user-attachments/files/15567830/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Yeah, MangaPlus support is currently broken in the public version but it has already been fixed in the nightly builds like reported in #831 and so it will work again with the next public release too 👍

Note: you can follow the status of the supported websites in the input dialog of the program, this way you always know if an issue has already be reported or not and if it has been solved 😉
![image](https://github.com/RedSquirrel87/manga-downloader/assets/1155596/6bf5168f-77a4-4e31-880c-0393f07ee24d)

**Comment by Pandeonidae** [comment]
Oh sick, thank you!
