### ISSUE TITLE
Downloading from Mangaplus doesn't work

### ISSUE THREAD

**Issue by sawyer787** [RedSquirrel87/manga-downloader#833]
Download from https://mangaplus.shueisha.co.jp/updates doesn't work. 

When I enter the link of the manga (whatever it is) that I want to download, an error message appears. I asked friends who use the program to check, and they confirmed the same problem.

**Comment by RedSquirrel87** [comment]
See #832

**Comment by sawyer787** [comment]
> Vedi #832
 
Thank you. Does this mean we will have to wait for the new version of the program? How long until it will be released?

**Comment by RedSquirrel87** [comment]
Yes, you have to wait for the next public release, there is not a fixed ETA on public release, usually it is released after a good number of updates and various fixes have accumulated. Looking at past major releases, this typically happens every three months or so. Otherwise, you could support the program by subscribing on its Patreon page, which gives you immediate access to the nightly builds that include fixes and updates as soon as they are implemented. However, this is entirely up to you and not mandatory, you can easily wait and get the same things for free later on 👍

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue
