### ISSUE TITLE
New Asura Domain

### ISSUE THREAD

**Issue by SpiralKipz** [RedSquirrel87/manga-downloader#835]
Asura's domain has changed to https://asuracomic.net/ and thus isn't working (plus it seems the structure changed). Maybe I'm dumb and it's as simple as using one of the generic framework bypasses, however.

**Comment by RedSquirrel87** [comment]
Thank you for reporting the issue, I'll fix this in next version 👍

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue

**Comment by RedSquirrel87** [comment]
v64.1 just released, it should fix the support for asuracomics again 👍 
In the end, they had simply changed the name of a class in the HTML code, but I preferred to write a specific and separate framework now since they keep changing it. This way, I avoid messing up the generic one even more, which is why it took me a while
