### ISSUE TITLE
installing issue in linux

### ISSUE THREAD

**Issue by mrteddy990** [RedSquirrel87/manga-downloader#836]
![Screenshot from 2024-08-01 08-55-38](https://github.com/user-attachments/assets/cd07ca23-ce88-47d8-8c0e-82c69f4b23f1)
i meet all the requirements after that it wont install in linux mint cinnamon 22 
what to do ?

**Comment by RedSquirrel87** [comment]
As stated on the website, to start it, you need to run this command from the terminal:
![image](https://github.com/user-attachments/assets/61a0b096-5b53-4157-ad8d-25bef69c7023)

Also remember that the terminal must be located in the same folder as the .jar file, you can change the folder where are you located with the following command:
`cd /home/user/xxxx`
obviously, you need to replace the path with the full one where your file is located (example: /home/omer/Downloads/MangaDownloader") if you extracted the ZIP in your Downloads folder.

Oh and another tip: from the path I see in the screenshot, you are trying to launch the program directly from inside the ZIP file. This won’t work because it will give you an error saying it can’t find the necessary libraries. You need to extract the ZIP file first so that all the files and the lib subfolder are extracted in the same folder, and only then start the executable with the command mentioned above 👍

**Comment by mrteddy990** [comment]
![Screenshot from 2024-08-01 16-11-17](https://github.com/user-attachments/assets/edf4e100-ddf4-4481-b835-7adfd627217e)
It's Finally working !!
Thanks a lot!!
