### ISSUE TITLE
"Error! Unable to detect the extension for the image file download" for MangaPark Mangas

### ISSUE THREAD

**Issue by nexist418** [RedSquirrel87/manga-downloader#837]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

All of my MangaPark mangas give me an error when downloading chapters.
https://mangapark.net/title/80100-ikusei-skill-wa-mou-iranai-to-yuusha-party-wo-kaikosareta-node-taishoku-kingawari-ni-moratta-ryouchi-wo-tsuyoku-shitemiru

Note there ar e 4 chapters, 13-16. Below is the log from Chapter 16.

`20:12:44:  Getting pages list for chapter Chapter 16...
20:12:45:  53 pages found for this chapter.
20:12:45:  Downloading pages...
20:12:46:  Error while downloading image at URL  https
20:12:46:  Trying again...
20:12:47:  Error while downloading image at URL  https
20:12:47:  Trying again...
20:12:48:  Error while downloading image at URL  https
20:12:48:  Trying again...
20:12:49:  Error while downloading image at URL  https
20:12:49:  Max retry attempts exceeded, image skipped.
20:12:50:  Error! Unable to detect the extension for the image file download at: https://mangapark.net/title/245767-en-danzai-sareta-akuyaku-reijou-wa-gyakkou-shite-kanpeki-na-akujo-wo-mezasu/8796974-chapter-16
20:12:50:  Usually this mean that the server returned HTML code instead of the image file or simply the image is corrupted.
20:13:59:  Chapter downloaded.
`

jvm_log.txt
[jvm_log.txt](https://github.com/user-attachments/files/16568311/jvm_log.txt)

**Comment by RedSquirrel87** [comment]
Yeah, as mentioned in the changelog (you can find a specific mention in #828 ), unfortunately the support for Mangapark v5x is currently makeshift and not optimized due to the way their framework is programmed. To put it briefly, in the JSON code they return, there is no way to distinguish images used on the web page from the actual images of the manga chapter. Therefore, the program ends up trying to download extra pages like advertisement banners, which obviously return errors. But don’t worry, even if you get errors during the download process (because of those adv images) , the chapter’s page images should still all downloaded correctly 👍

**Comment by nexist418** [comment]
Ah, I misunderstood then. I didn't realize that the file was still being created. 

Thank you.

**Comment by RedSquirrel87** [comment]
v64 released, it should fix this issue
