### ISSUE TITLE
webtoons doesn't work

### ISSUE THREAD

**Issue by mollydeep** [RedSquirrel87/manga-downloader#845]
After update at 62.3 Webtoons stopped working
[jvm_log.txt](https://github.com/user-attachments/files/16739530/jvm_log.txt)
Can you help, please?
How I can downgrade?
Thanks

**Comment by RedSquirrel87** [comment]
It seems a compatibility issue with the new Jsoup library, I'll try to fix this asap

**Comment by RedSquirrel87** [comment]
I just realized now that the compatibility error with Jsoup in your log is related to Batoto, not Webtoons. So for Webtoons, something has probably changed in the site's code, and I need to check

**Comment by RedSquirrel87** [comment]
I just tried to restore the old version of the Jsoup library that was changed in v64.3, and I can confirm that Webtoons still doesn’t work. So it’s not a new version issue; they’ve most likely broken support for this website in the app with some change. I will try to see if it can be fixed quickly, and if so, I’ll release another update today

**Comment by RedSquirrel87** [comment]
v64.4 released, it should fix both Batoto and Webtoons issues.
P.s.: I had to rewrite the Webtoons support from scratch because they changed several classes in their HTML code. And since I was at it, I also improved the framework so that it can load now the entire chapter list even when it’s split across multiple pages. Just be aware that very long lists (like manga with 20 or more pages) will require longer waiting times (because to avoid being mistakenly detected as a DDOS attack, I’ve set a random pause between 1 and 3 seconds when requesting each page).
