### ISSUE TITLE
[Webtoon] Page loading impossible since V64

### ISSUE THREAD

**Issue by Enaella** [RedSquirrel87/manga-downloader#849]
Hello,

Today I upgraded to V64.5 and noticed something. Every single link to webtoon titles have stopped working. Example
Link: https://www.webtoons.com/en/romance/one-husband-is-enough/list?title_no=6677
there is at least 7 chapters (today) but whenever I try to load the manga via the app, no chapters show. I tried with a few others I had in my favourite and every title on webtoon show no new chapters. I tried to load them (right click, open manga) empty.

**Comment by RedSquirrel87** [comment]
Webtoons support has been rewritten in v64.4 because it did not work anymore (#845 ), probably they changed something again. I will check as soon as I will be at home

**Comment by RedSquirrel87** [comment]
I checked, it seems that the problem is that now the program receives the mobile version of the site. They probably changed their code via server and now it no longer relies on the user-agent but on some other parameter (maybe web browser's window size?). So, without getting a valid param, the server responds by default showing the mobile version of the site, which obviously has all different classes in its HTML code. So now I either have to figure out the way they use to show the desktop version or rewrite the entire framework again to support the mobile version. Surely this site has become really annoying with these continuous changes 😅

**Comment by RedSquirrel87** [comment]
v64.6 released, it should fix this issue. Who knows for how long though 😂

**Comment by Enaella** [comment]
Awesome, I feel you. thanks a lot!
Now I can load the pages indeed, the only part not working is the checking for new chapters from bookmarks. 
![image](https://github.com/user-attachments/assets/b32565e0-21ac-41f1-beba-ec8da1fbfbd0)
been like that for the past 10 min, on one single title.

**Comment by RedSquirrel87** [comment]
Please could you paste here the content of the jvm_log.txt file?

**Comment by Enaella** [comment]
[jvm_log.txt](https://github.com/user-attachments/files/16816318/jvm_log.txt)

here you go

[Fri Aug 30 13:33:16 CEST 2024] 144 pages found for chapter Ep. 3 - The Misanthrope Duke
Exception in thread "Thread-19" java.lang.NoSuchMethodError: java.util.ArrayList.getLast()Ljava/lang/Object;
	at mainpackage.WebToons.GetChapters(WebToons.java:89)
	at mainpackage.Manga.GetNewChapters(Manga.java:791)
	at mainpackage.NewJFrame.GetChaptersList(NewJFrame.java:9474)
	at mainpackage.NewJFrame.UpdateChaptersList(NewJFrame.java:9672)
	at mainpackage.NewJFrame.CheckForNewChapters(NewJFrame.java:6889)
	at mainpackage.NewJFrame.CheckForNewChapters(NewJFrame.java:6913)
	at mainpackage.NewJFrame.access$39300(NewJFrame.java:162)
	at mainpackage.NewJFrame$232.run(NewJFrame.java:13349)
	at java.lang.Thread.run(Thread.java:748)

**Comment by RedSquirrel87** [comment]
Thank you, it seems that the getLast() method does not exist in the JRE (Java 8), it appears to have been introduced in later versions. You could fix it yourself by simply installing the JDK (Java 22), but I will release an update shortly with a backward-compatible function since this will likely be an issue affecting many, as most PC use the JRE by default and not the JDK 👍

**Comment by Enaella** [comment]
and that my friend is why I could never be a dev... thanks a bunch!

**Comment by RedSquirrel87** [comment]
I have released an update that fixes this issue. Since it was just a minimal change, I kept it as version v46.6 because even the changelog would have been the same. So don’t worry if it still shows the same version. The program checks the correct version at startup by comparing the SHA-1 hash, so there’s no risk it will use an old version 👍
