### ISSUE TITLE
Settings not persisting across restart of the app

### ISSUE THREAD

**Issue by jdeitsch** [RedSquirrel87/manga-downloader#854]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue

not relavant

>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

Nothing in the `jvm_log.txt` related to the failure to save

## Issue
Since the latest update, making changes to my `Settings` in the app (such as changing the output format from CBZ to EPUB or back) is not persisted from shutting down the app to reopening, so I need to switch it back every time I start up the program.

App version: 64.7

**Comment by RedSquirrel87** [comment]
Please be sure the app can write in the folder where is the executable (the JAR file) because in the latest versions the settings are stored to file now and not in system registry anymore

**Comment by jdeitsch** [comment]
Okay, I took the `readOnly` flag off the directory and that fixed it for the portions of the `settings.dat` that are associated with the "File Naming Scheme" menu, and it looks like the changes are saving for the "Download chapters as" value in the `.dat` but it's reverting to the previous value on startup.  Is there something I may need to clean up elsewhere?

**Comment by RedSquirrel87** [comment]
What's your OS?

**Comment by jdeitsch** [comment]
Windows 11

**Comment by RedSquirrel87** [comment]
The issue happens only with EPUB? Or for any format you choose?

**Comment by jdeitsch** [comment]
I had set it to epub to try out some of the metadata options available in epub and ultimately decided to go back to CBZ.  Now it defaults back to epub every time I start up the app.

I've tried switching to CBZ, PDF, or JPEG and it persists while the app is open, but reverts to epub when I restart the app

**Comment by jdeitsch** [comment]
I even tried changing it to CBZ, then changing a value in the formatting menu which saves the settings on "OK" and it updated the settings, but then when I closed and reopened the app, I was back on epub

**Comment by RedSquirrel87** [comment]
Ok, so is seems indeed to be an issue related to the EPUB format. Then please try this: unlink your Patreon account from the program with the specific function in the Extra -> Patreon menu and restart it. This way, since the EPUB format is exclusive to Patreon supporters, at startup, not recognizing you as a subscriber anymore, the program should force the output format to RAW and maybe that will unlock this weird loop.

P.s.: please try to save the settings a couple of times (and restart the program too) before to relink your Patreon account again, just to be sure

**Comment by jdeitsch** [comment]
So, it appears that attempting to unlink my Patreon account also doesn't work.  

I'm going to download a fresh copy of the app and try that.

**Comment by RedSquirrel87** [comment]
Please could you check your settings.dat file (just open it with any text editor) and tell me what are the stored values for the fields "OUT" and "patreon_out"?

**Comment by jdeitsch** [comment]
```
i|OUT=1

i|patreon_out=6
```

**Comment by jdeitsch** [comment]
I set up a second copy of the app and pulled my `.db` file over and manually entered my settings into those menus and it all seems to be working on the new copy.

**Comment by RedSquirrel87** [comment]
> i|patreon_out=6

Thank you, this information could be very useful for better identifying the bug. There must be something that doesn’t correctly save the _patreon_out_ parameter because 6 is indeed "EPUB", so it shouldn’t be there. This would also explain why this issue had never been reported to me before, because to encounter this problem two very limiting conditions must be met: being a Patreon subscriber and using the EPUB format. I will study the code more thoroughly to try to understand where the issue causing the bug is. In the meantime, I thank you for all the tests you have done and for reporting the problem (and of course for supporting the project) 🙏

**Comment by jdeitsch** [comment]
Thank you for the quick response and the helpful support and the awesome product

**Comment by RedSquirrel87** [comment]
I can confirm that this issue has now been fixed in the nightly builds and will be resolved in the next public release as well 👍
