### ISSUE TITLE
Trouble downloading from Lezhin 

### ISSUE THREAD

**Issue by sashakeista** [RedSquirrel87/manga-downloader#863]
Hello there, I have encountered problem downloading chapters from Lezhin for some titles, but I can also downloaded some of the titles. Is this related to Lezhin messed up image? Thanks

**Comment by RedSquirrel87** [comment]
Please remember to always attach or paste the content of the jvm_log.txt file when reporting a problem. Without this information, it's very difficult for me to identify where the issue might be.
Additionally, please remember to assign the issue to me when you post on GitHub, otherwise I don't receive the notification of the new issue created and may not notice it (which is why I'm only responding now, sorry)

**Comment by sashakeista** [comment]
here you go, btw can I ask how do I assign the issue to you? Thanks

[jvm_log.txt](https://github.com/user-attachments/files/17926515/jvm_log.txt)

**Comment by sashakeista** [comment]
also this
[jvm_log.txt](https://github.com/user-attachments/files/17928123/jvm_log.txt)

**Comment by sashakeista** [comment]
these logs are from 2 different series

**Comment by RedSquirrel87** [comment]
Thank you so much for sending the logs 👍 At first glance, it seems like there are indeed two different errors, so I certainly have a lot of starting material to analyze. I'll look into fixing the issues as soon as possible so that in the next major release planned for December I can already include a fix for both

**Comment by RedSquirrel87** [comment]
v70 just released, it should fix this issue 👍
