### ISSUE TITLE
First Launch Issue

### ISSUE THREAD

**Issue by ghost** [RedSquirrel87/manga-downloader#864]
I believe it's my lack and it's my first time use the app. I tried solve it by myself and it stucked here.
I tried to download from Batotoo (Status 'Working'), so I think it's invalid URL, I tried the example URL yet the same error occurred. The note said something about increase the timeout, so I increase it little by little until it reach the max, 300.
I don't know what else to solve, so here I am. Please help, thank you
![image](https://github.com/user-attachments/assets/52ad289c-7089-451b-a0b9-1967b07cbfde)

**Comment by RedSquirrel87** [comment]
Please remember to always attach or paste the content of the jvm_log.txt file when reporting a problem. Without this information, it's very difficult for me to identify where the issue might be.
Additionally, please remember to assign the issue to me when you post on GitHub, otherwise I don't receive the notification of the new issue created and may not notice it (which is why I'm only responding now, sorry)

**Comment by RedSquirrel87** [comment]
I'm closing this issue as I haven't received any further responses from the user. If needed, feel free to reopen or create a new issue.
