### ISSUE TITLE
kuragebunch.com with account cookies

### ISSUE THREAD

**Issue by Camtist** [RedSquirrel87/manga-downloader#868]
Hello! I am having trouble downloading the manga that I purchased through my account on kuragebunch.com. Specifically this one: https://kuragebunch.com/episode/3269754496843977538#

I tried using Manga Downloader Assistant to record the cookies for my account for the site on both Firefox and Chrome, copy-pasting them to the program in accordance with the instructions, but the program still only lists the free chapters (at the time of writing, chapters 1, 2, 40, and 41). There is no error or error log because it does still retrieve those free chapters. The other chapters are accessible to me in my browser. I also tried logging out of my account before retrieval, as the extension suggested, but no dice. If this is just a quirk of kuragebunch.com, the purchased chapters needing more than just cookies to be accessed or something, then oh well. Otherwise, any assistance would be greatly appreciated.

Thank you for making this wonderful tool.

**Comment by RedSquirrel87** [comment]
Hello, first of all, thank you for reaching out and for your kind words about the Manga Downloader project. I appreciate your support 🙏
Regarding the issue, downloading paid content has never been intentionally supported by the application because downloading manga itself is already a legal gray area and allowing users to download paid content with the possibility of redistributing it for free online (I'm not saying this is your case, but this is what usually happens) would quickly draw unwanted attention to the program. I am certain that it would not be long before DMCA takedown notices or lawsuits were filed, to which I would have no defense. This would inevitably lead to the abandonment of support for that specific website or possibly the shutdown of the entire project. This choice could certainly be questioned for its logic and perhaps its actual legal validity, but it has worked quite well so far, as I have not received a single complaint from website owners in almost seven years of the project's existence 😅
The addition of support for cookies was solely intended to enable users to access sites that require a valid login to view even free content. The fact that it might also grant access to paid content for some websites, is an unintended side effect. This is why, for the reasons mentioned above, I cannot provide support when the cookies method does not work.
The only thing I can do on my end in this case is to "unlock" the view of all chapters in the list in the next release, because that was indeed a code limitation (the program gets the full list but it shows only the free ones). However, if the cookies method still won't allow for the downloading of those chapters (because they might require some additional steps), I will be unable, for the aforementioned reasons, to offer support to work around this issue. 
Thank you for your understanding 👍

**Comment by RedSquirrel87** [comment]
v70 just released, now you can find an option in the Extra -> Coreview menu to show all the chapters available and not only the free ones 👍
