### ISSUE TITLE
Some bato url can't get the image

### ISSUE THREAD

**Issue by anggerpdsw** [RedSquirrel87/manga-downloader#869]
I don't know why some urls from bato websites can't get the images and only the folders are generated.

Example URL: https://readtoto.com/series/168284

**Comment by RedSquirrel87** [comment]
Please check your log (jvm_log.txt file), if you find an error similar to this:

> Error while downloading image:
java.io.IOException: Directory 'D:\Downloads\MangaDownloader\Manga\✧ ݂ Bahkan Jika Aku Dikurung Sampai Mati │ ٬٬ ℬy .\Chapter 23' could not be created

then it's an issue related to the Windows OS, which does not allow the use of special characters in folder names. A workaround would be to remove the name of the manga from the creation of the output path (you can do this in the Edit -> Filename scheme dialog). Anyway, I will try to fix this in the next version so that the program can bypass this issue automatically.

**Comment by RedSquirrel87** [comment]
v70 just released, it should fix this issue 👍
