### ISSUE TITLE
Batoto: cannot get chapter list

### ISSUE THREAD

**Issue by alexandriatale** [RedSquirrel87/manga-downloader#870]
>When you report an issue please be sure to:
>1. Include the URL of the manga and specify what its chapter gives the issue
>2. Paste/Upload the **jvm_log.txt** file! 
>You'll can find the jvm_log.txt file created automatically by the program in the same folder where the program's executable is.

I tried several batoto url, including this:

https://batotoo.com/series/71089/reminiscence-adonis
https://batotoo.com/series/85043/master-villainess-the-invincible

But it stuck on "getting chapter list" loading then I get error box. 

![Screenshot 2024-12-20 132345](https://github.com/user-attachments/assets/256ad828-f349-45a2-95ad-52f010406e1f)

![Screenshot 2024-12-20 132312](https://github.com/user-attachments/assets/16b8adce-09ae-4412-b521-94f10382988e)

I have already installed jdk 22, and when I look at other issue, I installed jdk 23 too, but the problem still persists. Please help. Thank you so much

**Comment by RedSquirrel87** [comment]
I just tried and got no issue here with that URL:
![image](https://github.com/user-attachments/assets/7ac0626e-5582-4475-aeac-3248af9c32d5)
It seems the issue might be on your side. Please attach (or paste the content of) the jvm_log.txt file after the issue occurs, so that we can investigate what happens in the program to cause the freeze.

**Comment by alexandriatale** [comment]
[jvm_log.txt](https://github.com/user-attachments/files/18208646/jvm_log.txt)

Is this correct? Thank you so much!

**Comment by RedSquirrel87** [comment]
Yes 👍

> [Fri Dec 20 13:21:45 WIB 2024] Error while performing HTTP HEAD request:
org.apache.http.conn.ConnectTimeoutException: Connect to batotoo.com:443 [batotoo.com/114.7.94.231] failed: Connect timed out

It looks like there's a problem with connecting to the website batotoo.com. The program tried to reach the website, but it took too long and timed out. This might be due to issues with your internet connection or the website itself, but since it's working fine on my end, it seems the problem is specific to your side.
Here's what you can try to fix it:
- Check your internet connection: Make sure you have a stable and active internet connection.
- Try accessing the website directly: Open your web browser and go to batotoo.com to see if you can connect to the website correctly.
- Try restarting your PC if you haven't already: this is particularly helpful after installing a JVM update to properly set the environment variables.
- Check your firewall or antivirus: check if you have any firewall or antivirus software that might be blocking the program's (or JVM) access to the internet. Adjust the settings to allow the program to connect.
- Test on another PC: if possible, try running the program on another computer on the same network. This will help determine if the issue is specific to the programs installed or the network configuration on your current machine.

**Comment by alexandriatale** [comment]
Thank you for your advice! I have tried most of your advice, and here is the result:

1. My internet connection is stable and active.
2. I can open the website directly on my web browser
3. I have restarted my laptop a few times prior, but I restarted again just in case, and the problem still persists
4. I paused my antivirus, but it still changes nothing
5. I haven't tried this because I don't have another pc, but I tried opening asura and it works fine. So maybe this only happen to batoto? I tried another website such as flame and scylla, but it seems now they have new websites so it cannot fetch the chapter lists too.

![Screenshot 2024-12-20 172630](https://github.com/user-attachments/assets/268915a9-d94f-43f7-9cbb-95be1ffab364)

**Comment by RedSquirrel87** [comment]
Have you tried any of the other batoto mirror websites? Does they work? For example:
https://zbato.com/series/71089/reminiscence-adonis
https://zbato.com/series/85043/master-villainess-the-invincible

or 

https://batotwo.com/series/71089/reminiscence-adonis

**Comment by alexandriatale** [comment]
I tried all the listed batoto websites, and some of them works! These are the ones:

https://readtoto.org/series/71089/adonis-official
https://readtoto.com/series/71089/adonis-official
https://xbato.net/series/71089/adonis-official

The others also can't work. Thank you so so much for your help! I'll try downloading them and fingers crossed it will work perfectly. Thank you!

**Comment by RedSquirrel87** [comment]
Is the error you get from other websites always the same (connection timeout)?

**Comment by alexandriatale** [comment]
Yes! All the same error
