### ISSUE TITLE
White Icon selection causes infinite loading and unresponsiveness

### ISSUE THREAD

**Issue by jdeitsch** [RedSquirrel87/manga-downloader#873]
Core program functionality.  When I tried to select the white icon option in the view menu to complement a chosen dark theme, the app loads forever and all buttons are non-responsive.

> jvm_log.txt
```
[Sat Dec 28 11:57:04 PST 2024] Program started.
[Sat Dec 28 11:57:04 PST 2024] MangaDownloader v64.7
[Sat Dec 28 11:57:04 PST 2024] OS: Windows 11 (amd64) | JVM: 23.0.1
[Sat Dec 28 11:57:05 PST 2024] Error while changing icons:
java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
	at mainpackage.NewJFrame.ChangeIcons(NewJFrame.java:6657)
	at mainpackage.NewJFrame.jRadioButtonMenuItem19ItemStateChanged(NewJFrame.java:13746)
	at mainpackage.NewJFrame.access$15000(NewJFrame.java:162)
	at mainpackage.NewJFrame$154.itemStateChanged(NewJFrame.java:5725)
	at java.desktop/javax.swing.AbstractButton.fireItemStateChanged(AbstractButton.java:2000)
	at java.desktop/javax.swing.AbstractButton$Handler.itemStateChanged(AbstractButton.java:2321)
	at java.desktop/javax.swing.DefaultButtonModel.fireItemStateChanged(DefaultButtonModel.java:460)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:374)
	at java.desktop/javax.swing.ButtonGroup.setSelected(ButtonGroup.java:166)
	at java.desktop/javax.swing.JToggleButton$ToggleButtonModel.setSelected(JToggleButton.java:356)
	at java.desktop/javax.swing.AbstractButton.setSelected(AbstractButton.java:346)
	at mainpackage.NewJFrame$218.run(NewJFrame.java:10506)
	at java.base/java.lang.Thread.run(Thread.java:1575)
Exception in thread "Thread-2" java.lang.NullPointerException: Cannot invoke "java.net.URL.toExternalForm()" because "location" is null
	at java.desktop/javax.swing.ImageIcon.<init>(ImageIcon.java:232)
	at mainpackage.NewJFrame$218.run(NewJFrame.java:10708)
	at java.base/java.lang.Thread.run(Thread.java:1575)

```

**Comment by RedSquirrel87** [comment]
First of all, thank you for reporting the issue. It's a very strange problem, though. I have just tested it and I can't reproduce the error on my end. From the error message, it seems that it can't find one of the icons in the default location (which is inside the executable JAR and not external, so it's unlikely you could have deleted it). I could guess it might be a problem specific to Windows 11 since I have Windows 10, but even so, I've introduced the new themes and icons months ago, and you're the first to report this issue so far. I find it a bit unlikely that no one has tested the icon change on Windows 11 until now, therefore I am inclined to exclude it as a problem related to the OS in general. 
The only thing I can suggest you is if you've already tried moving the program folder to another path (for example, to the desktop) to see if it might be a path issue (I'm just speculating, though it's worth a try). Let me know

**Comment by jdeitsch** [comment]
I just tried changing it to a path with no spaces in case that was the issue `c:/MangaDownloader/MangaDownloader.exe` with no change in behavior.  then I tried running it in compatibility mode in both the original path as well as the new path, with no change.

Is there a way to change the settings with a text editor so that I can at least start the program again?

**Comment by jdeitsch** [comment]
My currently saved `settings.dat` file is below, perhaps something is incorrect there?

> settings.dat
```
#--- PLEASE DO NOT EDIT THIS FILE MANUALLY! ---
#Sat Dec 28 12:26:44 PST 2024
b|FIRST=false
b|ZIP=false
b|ask=false
b|blackfix=false
b|chap_createfolder=false
b|chap_generatefromfields=false
b|chap_generatefrompattern=true
b|chap_include_date=false
b|chap_include_group=false
b|chap_include_lang=false
b|chap_include_manga=false
b|chap_include_uploader=false
b|chap_keeponlynumbers=false
b|chap_removemanganame=false
b|chap_setdigitspadding=false
b|chap_usecustomrules=false
b|chap_usemangacustomname=false
b|conc=false
b|conc_sameofchapter=true
b|conc_usechapcustomname=false
b|conc_usemangacustomname=false
b|darkmode=true
b|ex_replace=false
b|ex_skip=false
b|ex_suffix=true
b|general_empty=false
b|guess=false
b|lang_empty=true
b|manga_createfolder=true
b|manga_usecustomrules=false
b|manga_usemangacustomname=true
b|migration=true
b|onlyfolders=false
b|page_generatefromfields=false
b|page_generatefrompattern=true
b|page_include_chapter=false
b|page_include_group=false
b|page_include_lang=false
b|page_include_manga=false
b|page_include_uploader=false
b|page_usechapcustomname=false
b|page_usecustomrules=false
b|page_usemangacustomname=false
b|patreon_conc=false
b|patreon_page_generatefromfields=false
b|patreon_page_generatefrompattern=true
b|patreon_page_usecustomrules=false
b|pause_random=true
b|renaming_warn=false
b|show_completedwitherrors=true
b|show_confirm=false
i|CLVL=9
i|CONNTO=15
i|DIVIDER=252
i|FONTSIZE=11
i|HISTSIZE=5
i|IMGQ=95
i|OUT=1
i|PAUSE=1
i|READTO=15
i|RETRIES=3
i|ROWH=20
i|THREADS=2
i|cdelay=0
i|chap_maxchars=100
i|chap_rules=0
i|conc_maxchars=100
i|cpf1=0
i|cpf2=0
i|cpf3=2
i|frameh=710
i|framew=862
i|general_replacer=3
i|general_separator=0
i|manga_maxchars=50
i|manga_rules=0
i|page_maxchars=50
i|page_numberposition=0
i|page_rules=0
i|pause_end=30
i|pause_start=5
i|schedule_radio=0
i|startup=1
l|autobackuplast=1735412306118
s|PATH=C\:\\Users\\jdeit\\OneDrive\\Documents\\Manga
s|VER=64.7
s|chap_pattern=|M| - |C| (|L|)
s|conc_pattern=|M| - |C| (|L|)
s|general_emptyrep=X
s|lang=Any
s|lang_filter=EN
s|last101=https\://mangadex.org/title/30196491-8fc2-4961-8886-a58f898b1b3e/berserk-of-gluttony|\:|https\://mangadex.org/title/195023bf-cf9a-4772-94ef-09dd6eddea84/mahoutsukai-no-yome|\:|https\://mangadex.org/title/e9cc438f-46d9-4da2-872a-237f89caa7a6/is-my-second-life-a-healing-life|\:|https\://bato.to/series/161203/is-my-second-life-a-healing-life|\:|https\://mangadex.org/title/14610263-264a-4c22-8928-e4183e7d4719/i-ve-been-killing-slimes-for-300-years-and-maxed-out-my-level
s|last103=C\:\\Users\\jdeit\\OneDrive\\Documents\\Manga
s|page_pattern=|\#|
s|patreon={"access_token"\:"DC3ZWQV9Emm_wOc6I59Jv2pNBhyPXQP1TNQxTsgz4lw","refresh_token"\:"3VIEwUNWnrcpOWU2W5WCsCIiVkTOyc1VYMDxE57R6kQ","expires_in"\:2678400,"scope"\:"identity identity.memberships","token_type"\:"Bearer","expiresAt"\:"Jan 28, 2025 11\:01\:05 AM"}
s|patreon_page_pattern=|\#|
s|theme=com.formdev.flatlaf.intellijthemes.materialthemeuilite.FlatMaterialDeepOceanIJTheme
```

**Comment by jdeitsch** [comment]
okay, it looks like changing `b|darkmode=true` to `false` allows it to open again.

For reference, I am on a clean install of Windows, I had to do a full factory reset last night and was working on getting all of my programs set back up this morning when I started working on this.  I prefer dark mode in all of the everything I do, and I noticed that there was an Icon Color selector to give better contrast on the icons, so I flipped that switch and restarted the program only to find that it wouldn't complete startup anymore.

Running the latest JRE (`8u431`) and JDK (`23.0.1+11-39`) as of this morning (2024-12-28)

**Comment by RedSquirrel87** [comment]
Yes, change the: 
`b|darkmode=true`
to false to return to the black icons.
Anyway, I plan to release the new public version tomorrow, I will include a debug message that prints the path of the problematic icon on the screen, so we can properly verify what is and resolve it. I will also add a check to prevent the program from crashing in case it encounters a null icon (loading the old black icon instead), so it should at least no longer crash in these cases, but simply not load the white icon 👍

P.s.: I editd your message above by removing the part with your settings because it included your Patreon account token. Be careful in the future about posting such information publicly 😅

**Comment by RedSquirrel87** [comment]
v70 just released, it should fix this issue 👍
